### 필요라이브러리 불러오기

In [1]:
import keras
import os
import numpy as np
import pandas as pd
import collections
import pdf2image
from keras.preprocessing import image
import cv2 
import matplotlib.pyplot as plt
import time
import datetime
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.utils import to_categorical
import xml.etree.ElementTree as elemTree
import numpy as np

In [183]:
y_data = []
y_names = []
max_shape = []
for n in range(1,4):
    
    tree = elemTree.parse("./resource/scoreImg/random%s.xml"%n)
    sizeInfo = tree.find("./size")
    width = sizeInfo.find("./width").text
    height = sizeInfo.find("./height").text
    max_shape.append([height, width])
    inner_data = []
    for object in tree.findall("./object"):
        data ={}
        name = object.find('name').text
        if name not in y_names:
            y_names.append(name)
        bndbox = object.find('bndbox')
        xmin = int(bndbox.find("./xmin").text)
        ymin = int(bndbox.find("./ymin").text)
        xmax = int(bndbox.find("./xmax").text)
        ymax = int(bndbox.find("./ymax").text)
        data["bbox"] = [xmin, ymin, xmax, ymax, y_names.index(name)]
        inner_data.append(data)
    y_data.append(inner_data)
num_classes = len(y_names)
max_shape = np.array(max_shape).astype(int)
max_shape = np.max(max_shape, axis = 0)
print("맥스",max_shape)
img_list= []
for n in range(1,4):
    img = cv2.imread("./resource/scoreImg/random%s.png"%n, cv2.IMREAD_GRAYSCALE)
    img = np.where(img > 127, 0, 255)
    print(img.shape)
    if img.shape[0] < max_shape[0]:
        diff = max_shape[0]-img.shape[0]
        img = np.concatenate([img, np.zeros((diff,img.shape[1]))], axis = 0)
    if img.shape[1] < max_shape[1]:
        diff = max_shape[1]-img.shape[1]
        img = np.concatenate([img, np.zeros((img.shape[0], diff))], axis = 1)
    print(img.shape, '\n\n')
    img_list.append(img)
print(y_data[0][0].values())
for i in range(len(y_data)):
    y_data[i] = np.array([np.array(list(d.values())) for d in y_data[i]])
# plt.imshow(np.resize(img, (800,1100)))


model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(max_shape[0], max_shape[1], 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(5, activation='sigmoid'))

model.compile(optimizer='adam',
              loss=yolo_loss,
              metrics=['accuracy'])

# history = model.fit(train_ds, validation_data=val_ds, epochs=10)

[ 952 1204]
(952, 1204)
(952, 1204) 


(677, 1094)
(952, 1204) 


(677, 1097)
(952, 1204) 


dict_values([[187, 56, 293, 253, 0]])


ResourceExhaustedError: OOM when allocating tensor with shape[4516096,60] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:AddV2]

In [128]:
x_data = np.random.rand(10, 10) # 10개의 샘플을 가진 입력 데이터
y1_data = np.random.rand(10, 1) # 첫 번째 출력 값
y2_data = np.random.rand(10, 1) # 두 번째 출력 값
y_data = (y1_data, y2_data)

In [131]:
y1_data
y_data
x_data

array([[0.03367411, 0.51128272, 0.15991132, 0.3081908 , 0.68810003,
        0.6839447 , 0.49587453, 0.91002878, 0.4758665 , 0.2066778 ],
       [0.43242113, 0.96366866, 0.26927961, 0.68299468, 0.4181779 ,
        0.17635523, 0.38564657, 0.92019359, 0.19540946, 0.10220595],
       [0.53425512, 0.43676093, 0.39056161, 0.50836512, 0.5296451 ,
        0.62712274, 0.25107608, 0.48304638, 0.60732692, 0.81081329],
       [0.86179332, 0.53187397, 0.26524139, 0.70233216, 0.2187104 ,
        0.99580587, 0.21244938, 0.55372216, 0.06636947, 0.54490946],
       [0.12037863, 0.05511964, 0.01805227, 0.05155868, 0.13052577,
        0.33979988, 0.94589111, 0.63852765, 0.31979533, 0.6915263 ],
       [0.81595062, 0.99433308, 0.08694209, 0.23112384, 0.83614048,
        0.55141749, 0.15365059, 0.61463128, 0.43605938, 0.26886187],
       [0.64212184, 0.53680557, 0.58272102, 0.00915595, 0.9543678 ,
        0.18656727, 0.39805997, 0.29104867, 0.10674069, 0.26179472],
       [0.14150001, 0.70317752, 0.6015780

In [179]:
new_img_list = []
for i in img_list:
   i = i.reshape(i.shape[0], i.shape[1], 1)
   new_img_list.append(i.astype(int))
new_img_list = np.array(new_img_list)
model.fit(new_img_list,np.array([1,2,3]))

InvalidArgumentError: Graph execution error:

Detected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):
    File "c:\Users\qhfkd\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\Users\qhfkd\anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
      self.io_loop.start()
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\qhfkd\anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
      self._run_once()
    File "c:\Users\qhfkd\anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
      handle._run()
    File "c:\Users\qhfkd\anaconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
      await self.process_one()
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
      await dispatch(*args)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 367, in dispatch_shell
      await result
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 662, in execute_request
      reply_content = await reply_content
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 360, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
      return super().run_cell(*args, **kwargs)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2863, in run_cell
      result = self._run_cell(
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2909, in _run_cell
      return runner(coro)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3106, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3309, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\qhfkd\AppData\Local\Temp\ipykernel_28772\1695705505.py", line 6, in <cell line: 6>
      model.fit(new_img_list,np.array([1,2,3]))
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\engine\training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\engine\training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\engine\training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\engine\training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\engine\training.py", line 890, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\engine\training.py", line 948, in compute_loss
      return self.compiled_loss(
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\losses.py", line 139, in __call__
      losses = call_fn(y_true, y_pred)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\losses.py", line 243, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\losses.py", line 1860, in sparse_categorical_crossentropy
      return backend.sparse_categorical_crossentropy(
    File "c:\Users\qhfkd\anaconda3\lib\site-packages\keras\backend.py", line 5238, in sparse_categorical_crossentropy
      res = tf.nn.sparse_softmax_cross_entropy_with_logits(
Node: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'
Received a label value of 3 which is outside the valid range of [0, 3).  Label values: 3 1 2
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_2536]

In [175]:
for i in real_y_data:
    for j in i:
        print(j.dtype)
real_y_data

int32
int32
int32
int32
int32
int32
int32
int32
int32
int32
int32
int32
int32
int32
int32


[(array([ 187,   49,  124,  290,  426,  553,  662,  754,  863,  954, 1047]),
  array([ 56, 187, 406, 287, 189, 367,  65, 315, 417,  44, 291]),
  array([ 293,  154,  185,  388,  531,  613,  759,  853,  966, 1013, 1106]),
  array([253, 383, 600, 496, 386, 559, 274, 526, 615, 236, 483]),
  array([0, 0, 1, 2, 0, 1, 2, 2, 0, 1, 1])),
 (array([ 37, 183, 370, 519, 681, 927, 188, 364, 491, 608, 795]),
  array([103,  35,  81,  73,  75, 135, 346, 410, 363, 385, 358]),
  array([137, 287, 470, 579, 786, 989, 295, 469, 549, 707, 853]),
  array([314, 233, 294, 265, 271, 328, 543, 610, 557, 595, 551]),
  array([2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1])),
 (array([ 46, 199, 406, 519, 691, 965, 167, 284, 493, 616, 941]),
  array([111,  36,  83, 204,  80, 136, 441, 380, 425, 454, 343]),
  array([ 169,  289,  478,  563,  824, 1005,  221,  431,  536,  684, 1023]),
  array([374, 200, 235, 349, 328, 266, 540, 655, 562, 601, 613]),
  array([2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1]))]

In [160]:
real_y_data = []
for j in range(len(y_data)):
    li = []

    for data in y_data[j]:
        li.append(data["bbox"])
    li = np.array(li)
    new = []
    for i in range(li.shape[1]):
        new.append(li[:,i])
    y_data_each = tuple(new)
    real_y_data.append(y_data_each)
real_y_data

[(array([ 187,   49,  124,  290,  426,  553,  662,  754,  863,  954, 1047]),
  array([ 56, 187, 406, 287, 189, 367,  65, 315, 417,  44, 291]),
  array([ 293,  154,  185,  388,  531,  613,  759,  853,  966, 1013, 1106]),
  array([253, 383, 600, 496, 386, 559, 274, 526, 615, 236, 483]),
  array([0, 0, 1, 2, 0, 1, 2, 2, 0, 1, 1])),
 (array([ 37, 183, 370, 519, 681, 927, 188, 364, 491, 608, 795]),
  array([103,  35,  81,  73,  75, 135, 346, 410, 363, 385, 358]),
  array([137, 287, 470, 579, 786, 989, 295, 469, 549, 707, 853]),
  array([314, 233, 294, 265, 271, 328, 543, 610, 557, 595, 551]),
  array([2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1])),
 (array([ 46, 199, 406, 519, 691, 965, 167, 284, 493, 616, 941]),
  array([111,  36,  83, 204,  80, 136, 441, 380, 425, 454, 343]),
  array([ 169,  289,  478,  563,  824, 1005,  221,  431,  536,  684, 1023]),
  array([374, 200, 235, 349, 328, 266, 540, 655, 562, 601, 613]),
  array([2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1]))]

In [161]:
real_y_data

[(array([ 187,   49,  124,  290,  426,  553,  662,  754,  863,  954, 1047]),
  array([ 56, 187, 406, 287, 189, 367,  65, 315, 417,  44, 291]),
  array([ 293,  154,  185,  388,  531,  613,  759,  853,  966, 1013, 1106]),
  array([253, 383, 600, 496, 386, 559, 274, 526, 615, 236, 483]),
  array([0, 0, 1, 2, 0, 1, 2, 2, 0, 1, 1])),
 (array([ 37, 183, 370, 519, 681, 927, 188, 364, 491, 608, 795]),
  array([103,  35,  81,  73,  75, 135, 346, 410, 363, 385, 358]),
  array([137, 287, 470, 579, 786, 989, 295, 469, 549, 707, 853]),
  array([314, 233, 294, 265, 271, 328, 543, 610, 557, 595, 551]),
  array([2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1])),
 (array([ 46, 199, 406, 519, 691, 965, 167, 284, 493, 616, 941]),
  array([111,  36,  83, 204,  80, 136, 441, 380, 425, 454, 343]),
  array([ 169,  289,  478,  563,  824, 1005,  221,  431,  536,  684, 1023]),
  array([374, 200, 235, 349, 328, 266, 540, 655, 562, 601, 613]),
  array([2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1]))]

In [134]:
y_data = []
y_names = []
max_shape = []
for n in range(1,4):
    
    tree = elemTree.parse("./resource/scoreImg/random%s.xml"%n)
    sizeInfo = tree.find("./size")
    width = sizeInfo.find("./width").text
    height = sizeInfo.find("./height").text
    max_shape.append([height, width])
    inner_data = []
    for object in tree.findall("./object"):
        data ={}
        name = object.find('name').text
        if name not in y_names:
            y_names.append(name)
        bndbox = object.find('bndbox')
        xmin = int(bndbox.find("./xmin").text)
        ymin = int(bndbox.find("./ymin").text)
        xmax = int(bndbox.find("./xmax").text)
        ymax = int(bndbox.find("./ymax").text)
        data["bbox"] = [xmin, ymin, xmax, ymax, y_names.index(name)]
        inner_data.append(data)
    y_data.append(inner_data)
num_classes = len(y_names)
max_shape = np.array(max_shape).astype(int)
max_shape = np.max(max_shape, axis = 0)
print(max_shape)
img_list= []
for n in range(1,4):
    img = cv2.imread("./resource/scoreImg/random%s.png"%n, cv2.IMREAD_GRAYSCALE)
    img = np.where(img > 127, 0, 255)
    print(img.shape)
    if img.shape[0] < max_shape[0]:
        diff = max_shape[0]-img.shape[0]
        img = np.concatenate([img, np.zeros((diff,img.shape[1]))], axis = 0)
    if img.shape[1] < max_shape[1]:
        diff = max_shape[1]-img.shape[1]
        img = np.concatenate([img, np.zeros((img.shape[0], diff))], axis = 1)
    print(img.shape, '\n\n')
    img_list.append(img)
# plt.imshow(np.resize(img, (800,1100)))

[ 952 1204]
(952, 1204)
(952, 1204) 


(677, 1094)
(952, 1204) 


(677, 1097)
(952, 1204) 




In [115]:
for i in range(len(y_data)):
    y_data[i] = np.array([np.array(list(d.values())) for d in y_data[i]])
y_data 

C:\Users\qhfkd\AppData\Local\Temp\ipykernel_28772\1740156876.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y_data[i] = np.array([np.array(list(d.values())) for d in y_data[i]])


[array([[list(['187', '56', '293', '253']), 0],
        [list(['49', '187', '154', '383']), 0],
        [list(['124', '406', '185', '600']), 1],
        [list(['290', '287', '388', '496']), 2],
        [list(['426', '189', '531', '386']), 0],
        [list(['553', '367', '613', '559']), 1],
        [list(['662', '65', '759', '274']), 2],
        [list(['754', '315', '853', '526']), 2],
        [list(['863', '417', '966', '615']), 0],
        [list(['954', '44', '1013', '236']), 1],
        [list(['1047', '291', '1106', '483']), 1]], dtype=object),
 array([[list(['37', '103', '137', '314']), 2],
        [list(['183', '35', '287', '233']), 0],
        [list(['370', '81', '470', '294']), 2],
        [list(['519', '73', '579', '265']), 1],
        [list(['681', '75', '786', '271']), 0],
        [list(['927', '135', '989', '328']), 1],
        [list(['188', '346', '295', '543']), 0],
        [list(['364', '410', '469', '610']), 0],
        [list(['491', '363', '549', '557']), 1],
        [l

In [35]:
print(y_names)
y_data
print(sizeInfo.find("./width").text)


['pal', 'sa', 'sipyuck']
1097
